server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: ${DATASOURCE_DIALECT}
    hibernate:
      ddl-auto: update

management:
  server:
    port: 7001

logging:
  level:
    root: INFO
    com.glitchtako.forum: DEBUG